### ISSUE TITLE
Initialization of the Appetizer fails

### ISSUE THREAD

**Issue by hunterra** [appetizerio/replaykit.py#1]
Try to initialize the Appetizer with command
`appetizer = Appetizer(toolkit='D:\\Programs\\replaykit\\win32')`
This command fails with trace

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "d:\Programs\WinPython\WinPython-32bit-3.4.4.6Qt5\python-3.4.4\lib\site-packages\appetizer\ap
petizer.py", line 229, in __init__
    self.check_version(Appetizer.COMPAT_LEVEL)
  File "d:\Programs\WinPython\WinPython-32bit-3.4.4.6Qt5\python-3.4.4\lib\site-packages\appetizer\ap
petizer.py", line 232, in check_version
    v = json.loads(self.check_output(['version']))
  File "d:\Programs\WinPython\WinPython-32bit-3.4.4.6Qt5\python-3.4.4\lib\site-packages\appetizer\ap
petizer.py", line 240, in check_output
    return subprocess.check_output(self.program + args)
  File "d:\Programs\WinPython\WinPython-32bit-3.4.4.6Qt5\python-3.4.4\lib\subprocess.py", line 607,
in check_output
    with Popen(*popenargs, stdout=PIPE, **kwargs) as process:
  File "d:\Programs\WinPython\WinPython-32bit-3.4.4.6Qt5\python-3.4.4\lib\subprocess.py", line 859,
in __init__
    restore_signals, start_new_session)
  File "d:\Programs\WinPython\WinPython-32bit-3.4.4.6Qt5\python-3.4.4\lib\subprocess.py", line 1114,
 in _execute_child
    startupinfo)
PermissionError: [WinError 5] 

Environment: Windows 7 x64, Python 3.4.4

**Comment by mingyuan-xia** [comment]
Please read the doc.
the path should point to an exe not the folder
https://github.com/appetizerio/replaykit.py/wiki#usage

**Comment by hunterra** [comment]
The folder "D:\\Programs\\replaykit\\win32" contains "replaykit.exe" file. Anyway the error appears.
The correct way is to give the full path to exe file like this "D:\\Programs\\replaykit\\win32\\replaykit.exe", not to the folder containing exe.
